### ISSUE TITLE
SubTitles are not working

### ISSUE THREAD

**Issue by nidhinkumar06** [nkoehler/mat-video#12]
In the document subtitles feature is available using track but i have tried using the track but couldn't get the track.

#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Doesn't show subtitle feature

#### What is the expected behavior?
Should display the subtitle feature

#### What are the steps to reproduce?
<track matVideoTrack src={{englishTitle}} kind="captions" srclang="en" label="English">
<track  src={{tamilTitle}} kind="captions" srclang="ta" label="Tamil">

**Comment by nkoehler** [comment]
Unless you have other evidence to provide, subtitles are working as confirmed here.

![image](https://user-images.githubusercontent.com/10172004/53252047-12c91480-368c-11e9-81d3-c02956d0df0c.png)

Code
```html
<mat-video src="/assets/friday.mp4">
        <track matVideoTrack default kind="subtitles" srclang="en" src="/assets/friday.vtt" />
</mat-video>
```
Video is from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track)

Closing.

**Comment by matiasmagni** [comment]
I'm experimenting the same issue!

**Comment by sibtcha** [comment]
Me too
