### ISSUE TITLE
seeking option in mat-video, how to use it ?

### ISSUE THREAD

**Issue by rajatsehgal2010** [nkoehler/mat-video#15]
i want to seek into a video at particular duration, how can i do it ?

**Comment by nkoehler** [comment]
In your HTML file:

```html
<mat-video #video src="localOrRemoteVideo.mp4"></mat-video>
```

In your TS file:
```ts
export class SampleComponent implements OnInit {
  @ViewChild('video') matVideo: MatVideoComponent;
  video: HTMLVideoElement;

  constructor() { }

  ngOnInit(): void {
    this.video = this.matVideo.getVideoTag();

    this.video.currentTime = 10; // set video time position to 10 seconds
  }
}
```
The API feature is experimental and subject to change.

Closing.

**Comment by rajatsehgal2010** [comment]
i am unable to import the MatVideoComponent ? can you please tell how to do
it

**Comment by rajatsehgal2010** [comment]
can't import MatVideoComponent, showing this warning in ts file that cannot
import MatVideoComponent. Please help me in this.

**Comment by nkoehler** [comment]
[Read the instructions.](https://github.com/nkoehler/mat-video#installation)

**Comment by rajatsehgal2010** [comment]
still i can't import the MatVideoComponent

**Comment by rajatsehgal2010** [comment]
the mat-video package that we install using the

npm install --save mat-video

doesn't have the export functionality of the matvideocomponent and the src
video component is different from what you have provided at your github
repo.
So which i have to install , if i am using npm then many functionalities
aren't working.

**Comment by rajatsehgal2010** [comment]
this is the difference between them

**Comment by docaohuynh** [comment]
@rajatsehgal2010 
Add this line to _mat-video.d.ts_
`export * from './app/video/video.component';`
And in your component import 
`import { MatVideoComponent } from 'mat-video';
`
Still warning but It work
