### ISSUE TITLE
Export subcomponents

### ISSUE THREAD

**Issue by bastienlemaitre** [nkoehler/mat-video#16]
Hello,

Would it be possible to export the subcomponents linked to this library?
Indeed, I would like to change the appearance of the video player and keep the related subcomponents.

Thank you

**Comment by nkoehler** [comment]
Hi there,

If you plan on keeping the subcomponents and just changing the appearance, you would be better off using CSS?

![image](https://user-images.githubusercontent.com/10172004/55744506-1b3e9a00-5a03-11e9-9a73-6779d8a6387f.png)

**Comment by nkoehler** [comment]
Due to no further discussion from the author, this issue will be closed.
