### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by johnqiuwan** [nkoehler/mat-video#19]
#### Bug, feature request, or proposal:
It always shows a loading icon on ios

#### What is the current behavior?
always shows a loading icon on ios until a click 

#### What is the expected behavior?
Hide the loading icon after the video loaded 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://nkoehler.github.io/mat-video/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, ios, Safari

#### Is there anything else I should know?
Also, the Chrome on safari, the css is not quite right. the loading bar is in the middle, and also it will automatically into full screen mode when click play icon

**Comment by nkoehler** [comment]
Thank you for reporting the issue.  In the next release, iOS devices will properly hide the loading icon when data is loaded.

Regarding the CSS issue, Safari will automatically enter a special video mode when watching a video in mat-video.  This is normal behaviour and happens for all video players within the browser on iOS, not just mat-video.  Unfortunately, nothing can be done at this time to change this.
