### ISSUE TITLE
The latest version is not included in npm registry

### ISSUE THREAD

**Issue by KubaKocieba** [nkoehler/mat-video#20]
The latest version is not included in npm registry.
Not much more to say...

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by nkoehler** [comment]
The latest version is still being worked on, therefore it has not been released.  Closing.
