### ISSUE TITLE
Youtube video embed issue

### ISSUE THREAD

**Issue by akshaybhagwat76** [nkoehler/mat-video#26]
I was trying to to embed youtube video in this  <mat-video #vid [ngClass]="ngclass" [src]="'https://www.youtube.com/watch?v=TbJSABCCtt8" /> but its throwing this error,  may i know youtube videos are allowd.?
![youtubeurl](https://user-images.githubusercontent.com/26058268/59345701-4e1c4b80-8d2e-11e9-89c2-c282da4e50a0.PNG)

**Comment by nkoehler** [comment]
YouTube videos are not supported and there is no planned support for them in the future.  mat-video supports mp4 video files.
