### ISSUE TITLE
Edge browser issue

### ISSUE THREAD

**Issue by yuveliremil** [nkoehler/mat-video#29]
In Edge browser video spinner always visible.

**Comment by tpasquet** [comment]
In ui/mat-video-spinner, the line : 
`this.video.onloadeddata = () => this.videoLoaded = true;` may be the problem.

According to the MSDN doc for GlobalEventHandlers.onloadeddata, the compatibilty with Edge is unknown.

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onloadeddata

**Comment by nkoehler** [comment]
As Edge now runs on Chromium, I believe this is solved. Closing.
