### ISSUE TITLE
Unable to install MatVideoModule

### ISSUE THREAD

**Issue by mohdimran043** [nkoehler/mat-video#35]
#### Bug, feature request, or proposal:
After running the following command in the angular project. I am getting error in the browser as shown in the image below.

npm install --save @angular/material @angular/cdk @angular/animations hammerjs
npm install --save mat-video

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatVideoModule } from 'mat-video';
 
@NgModule({
  imports: [
    BrowserAnimationsModule,
    MatVideoModule
  ],
})

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/8122155/63212412-e22ed880-c10c-11e9-9dcf-c73e84721b16.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by nkoehler** [comment]
Please answer which version of angular/material/typescript/etc. you are using if you wish to receive help.

**Comment by mohdimran043** [comment]
Hey Sorry for the delayed response but the problem was that i was using angular 7 when i upgraded my angular everything started working as expected!..
