### ISSUE TITLE
simultaneously play multiple video sources

### ISSUE THREAD

**Issue by MoAsmar** [nkoehler/mat-video#36]
#### Feature request / Question:
Can I use multiple video sources that play continuously one after the other? 

I want to know if this functionality needs a custom implementation, or already exist in the component and can be used easily.

**Comment by nkoehler** [comment]
There is no existing implementation for this.  You can achieve this by listening to the video 'ended' event and setting the source to the next video in a playlist.

**Comment by MoAsmar** [comment]
Yes, I tried that and it worked, thank you.
