### ISSUE TITLE
Spinner appear even if video is loaded and playing

### ISSUE THREAD

**Issue by MoAsmar** [nkoehler/mat-video#38]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
When I move forward in the video to an unloaded clip, The video loads but loader keeps showing even if the video was loaded and started playing, the loader stays there unless you close the video and open it again.

#### What is the expected behavior?
it should disappear after clip loads.

#### What are the steps to reproduce?
https://angular-mat-video-loading-issue.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8, all browsers.

**Comment by nkoehler** [comment]
Working for me in Chrome.  Anymore details?

**Comment by MoAsmar** [comment]
No, I am not using it anymore so, thanks.

**Comment by nkoehler** [comment]
Closing
