### ISSUE TITLE
I need more control over the video API, this is not a bug.

### ISSUE THREAD

**Issue by corderogerardo** [nkoehler/mat-video#4]
#### feature request, or proposal:
I'm developing a landing with a video player, where I have a Video with mat-video, the thing is that I need to know when the video has ended, that's why I think  I need to access the video player API, to get the current time and total time and compare both, or simply listen to an ended event listener.

#### What is the current behavior?
No knowing how to gain more control over the video API.

#### What is the expected behavior?
Been able to play, stop, the video from the API.

#### What are the steps to reproduce?
Just install the component.

#### What is the use-case or motivation for changing an existing behavior?
Curiosity, learning, build something personal.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, TypeScript 5.

#### Is there anything else I should know?
Great component, pretty cool.

**Comment by nkoehler** [comment]
I plan to add a feature allowing the use of the raw HTML video element, which will allow you to create your own event listeners, or wait for the ended flag.  

The raw HTML video element API can be found [here](https://www.w3.org/2010/05/video/mediaevents.html).

The update for mat-video should be available within a week.

**Comment by nkoehler** [comment]
Release 2.3.0 is now available on npm, containing the ability to directly access the HTML5 video element and listen to events.  

The README has been updated showing an example of this.  In addition, the HTML5 video element has play()/pause() methods built into it which you can use for your personal projects.

As a note, this feature is experimental, and is subject to change in the future.  But for your purposes, it should be more than enough to work with.

Closing this issue as it has been addressed and verified working for the provided examples
