### ISSUE TITLE
Getting time where I stopped the video in between

### ISSUE THREAD

**Issue by BNRao** [nkoehler/mat-video#42]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

I need to get the time where I stopped the video 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

Requirement for my project

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 7

**Comment by nkoehler** [comment]
The following will set the video time to a typescript variable: `currentTime: number`

```html
<mat-video [src]="src" [(time)]="currentTime"></mat-video>
```

When you stop the video, just check the value of `currentTime`

Closing.
