### ISSUE TITLE
Playback not working on mobile

### ISSUE THREAD

**Issue by g-hamilton** [nkoehler/mat-video#43]
#### Bug, feature request, or proposal:

This appears to be a bug. Tested in iOS using Chrome browser. Not an issue on desktop - Chrome for MacOS works perfectly.

#### What is the current behavior?

Navigate to https://nkoehler.github.io/mat-video/ using Chrome on an iOS mobile device. Tap on the video to start playback. Video is jumpy / keeps freezing. Poor playback experience.

#### What is the expected behavior?

Video should play smoothly while streaming.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

As above. You can reproduce using the demo page on mobile.

#### What is the use-case or motivation for changing an existing behavior?

Users are complaining

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tested on Angular 8, iOS, Chrome. Other browsers / devices not tested.

#### Is there anything else I should know?

I didn't wait for the spinner to disappear before tapping on the video to start playback. Should I? My users certainly don't. Thanks

**Comment by nkoehler** [comment]
It's a 1080p video, so it's likely the connection is poor.  Tapping play before the video has buffered would most definitely do that as well, which mimics how the standard HTML5 video tag works. Since the title is misleading, I'm closing this issue.  Feel free to open another issue with a more accurate title.
