### ISSUE TITLE
How do you catch / handle errors with mat-video?

### ISSUE THREAD

**Issue by born2net** [nkoehler/mat-video#48]
How do you catch / handle errors with mat-video?
I have tried: ```this.renderer.listen(video, 'error', () => console.log('video ended'));```
but no luck.

in my case I am trying to load flv videos and receive an error (which I am not sure even why as the video is H.264 encoded).
tx,
Sean.

**Comment by born2net** [comment]
new ideas?
tx

**Comment by nkoehler** [comment]
mat-video supports the same formats as the [HTML5 video tag](https://www.w3schools.com/tags/tag_video.asp).  Most browsers do not support FLV for this.

You will need a separate library and video player for flv videos. https://stackoverflow.com/questions/18414015/how-to-play-flv-video-in-html-video-tags

Closing.

**Comment by born2net** [comment]
thank you...
