### ISSUE TITLE
Disable shortcuts if needed.

### ISSUE THREAD

**Issue by BoJIbFbI4** [nkoehler/mat-video#6]
#### Request, or proposal:

Disable shortcuts if needed.

#### What is the current behavior?

if you have some input on the page with mat-video and type 'f', => open fullscreen mode.

#### What is the expected behavior?

choose to disable shortcuts attribute

#### What are the steps to reproduce?
you can reproduce in your example.

**Comment by nkoehler** [comment]
Version 2.5.0 has been released which addresses this issue.  You can now disable keyboard shortcuts by using the "keyboard" attribute and setting it to false.  The readme has been updated as well.

Example:
`<mat-video src="video.mp4" [keyboard]="false"></mat-video>`

Thank you for your patience and support.
