### ISSUE TITLE
Video controls are not viewable on videos that have light background

### ISSUE THREAD

**Issue by DenisaSurdu** [nkoehler/mat-video#9]
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?

Video controls on white-ish video are not visible (they are on the video, but because the background is white and the controls are white, you can't see them with the naked eye) 

In the screenshot I have a recording of a website that I want to render to the user:
![screenshot from 2019-01-17 18-10-23](https://user-images.githubusercontent.com/4330214/51376826-333c0700-1b01-11e9-9c2d-9b077670e137.png)

#### What is the expected behavior?

Have the possibility to change the control colors or have a gradient that will allow buttons to be viewable. 

#### What are the steps to reproduce?

Use a video that has light background with the default values of mat-video.

#### What is the use-case or motivation for changing an existing behavior?

Clients have requested viewing online recordings of their websites when there are errors on their website pages. I have no control over client website design decisions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 7.0.3
`"@angular/material": "7.0.3",`
`"mat-video": "2.5.0"`
` "typescript": "3.1.6"`

Any browsers and OS

#### Is there anything else I should know?

n/a

**Comment by nkoehler** [comment]
Version 2.5.1 of mat-video is now available.  This release adds a gradient which allows the buttons to be visible for videos with light backgrounds.  As such, this issue will be closed.
